name: Bug Report
description: Create a report to help us improve
labels: [ bug, new issue ]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Carefully read and work through this check list in order to prevent the most common mistakes and misuse of CoreX:
      options:
        - label: I'm reporting a bug unrelated to a specific site.
          required: false
        - label: I've verified that I'm running the latest [**stable version**](https://github.com/mcbabo/CoreX/releases/latest/) of CoreX or other.
          required: true
        - label: I've read the [**Contributing guidelines**](https://github.com/mcbabo/CoreX/blob/master/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/mcbabo/CoreX/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.
          required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description:
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: false

  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: |
        Steps to reproduce the behavior:
        1.Go to '...'
        2.Click on '....'
        3.Scroll down to '....'
        4.See error
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error reports
      placeholder: |
        Click on the displayed error report to copy it.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots & Screen Records
      placeholder: |
        Screenshots & Screen Records can amp up bug reports.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description:
      placeholder: |
        Add any other context about the problem here. (Android version, device model, etc.)